# Generated by Django 4.2.29 on 2026-04-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_gitrepository'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='linked_commit_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='linked_commit_sha',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='ticket',
            name='origin_commit_sha',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
