# Generated by Django 4.2.29 on 2026-04-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_ticket_linked_commit_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='linked_commit_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
